name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build API
        run: |
          cd apps/api
          pnpm db:generate
          pnpm build
          
      - name: Build Web
        run: |
          cd apps/web
          VITE_API_URL=/api pnpm build
          
      - name: Verify Builds
        run: |
          echo "Checking API build..."
          ls -la apps/api/dist/
          echo "Checking Web build..."
          ls -la apps/web/dist/
          
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
